name: Automatisation des tests DevSecOps

on: push

jobs:
  Dependances:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Scan dependencies with Trivy
        uses: aquasecurity/trivy-action@master
        with:
           scan-type: fs
           scan-ref: '.'
           severity: HIGH,CRITICAL
           ignore-unfixed: true
           exit-code: 1

  Dockerfile:
    runs-on: ubuntu-latest
    needs: Dependances
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name : Create Image
        run: |
            docker build -t imgvulne:2.1 .
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
           scan-type: image
           image-ref: 'imgvulne:2.1'
           severity: HIGH,CRITICAL
           ignore-unfixed: true
           exit-code: 1

  Deploy:
    runs-on: ubuntu-latest
    needs: Dockerfile
    steps:
      - name: Deploy
        run: echo "Rien à faire ici. Votre application est prête à être déployée"
